// <auto-generated/> - Sample code for learning purposes
// EquatableArray<T> wrapper for ImmutableArray<T> with structural equality.
// Required because ImmutableArray<T> uses reference equality, which breaks caching.

using System.Collections;
using System.Collections.Immutable;

namespace MyGenerators;

/// <summary>
/// Wraps <see cref="ImmutableArray{T}"/> with structural (value-based) equality.
/// Use this in generator model types instead of raw ImmutableArray to ensure
/// the incremental pipeline caches correctly.
/// </summary>
public readonly struct EquatableArray<T>(ImmutableArray<T> array)
    : IEquatable<EquatableArray<T>>, IEnumerable<T>
    where T : IEquatable<T> {

    public static readonly EquatableArray<T> Empty = new(ImmutableArray<T>.Empty);

    /// <summary>Gets the underlying immutable array.</summary>
    public ImmutableArray<T> Array { get; } = array.IsDefault ? ImmutableArray<T>.Empty : array;

    /// <summary>Gets the number of elements.</summary>
    public int Length => Array.Length;

    /// <summary>Gets the element at the specified index.</summary>
    public T this[int index] => Array[index];

    /// <summary>Returns true if the arrays contain equal elements in the same order.</summary>
    public bool Equals(EquatableArray<T> other) =>
        Array.AsSpan().SequenceEqual(other.Array.AsSpan());

    public override bool Equals(object? obj) =>
        obj is EquatableArray<T> other && Equals(other);

    public override int GetHashCode() {
        var hash = new HashCode();
        foreach (var item in Array) {
            hash.Add(item);
        }
        return hash.ToHashCode();
    }

    public static bool operator ==(EquatableArray<T> left, EquatableArray<T> right) =>
        left.Equals(right);

    public static bool operator !=(EquatableArray<T> left, EquatableArray<T> right) =>
        !left.Equals(right);

    public ImmutableArray<T>.Enumerator GetEnumerator() => Array.GetEnumerator();
    IEnumerator<T> IEnumerable<T>.GetEnumerator() => ((IEnumerable<T>)Array).GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => ((IEnumerable)Array).GetEnumerator();

    public static implicit operator EquatableArray<T>(ImmutableArray<T> array) => new(array);
    public static implicit operator ImmutableArray<T>(EquatableArray<T> array) => array.Array;
}
