// <auto-generated/> - Sample code for learning purposes
// Unit test template for source generators using CSharpGeneratorDriver.
// Uses xUnit. C# 14 patterns, K&R style.

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace MyGenerators.Tests;

public class AutoToStringGeneratorTests {
    [Fact]
    public void GeneratesToString_ForAnnotatedPartialClass() {
        var source = """
            using MyGenerators;

            namespace TestApp;

            [AutoToString]
            public partial class Person {
                public string Name { get; set; } = "";
                public int Age { get; set; }
            }
            """;

        var result = RunGenerator<AutoToStringGenerator>(source);

        // No errors
        Assert.Empty(result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

        // Generated file exists
        var generated = Assert.Single(
            result.Results[0].GeneratedSources,
            s => s.HintName == "Person.AutoToString.g.cs");

        var text = generated.SourceText.ToString();

        // Verify generated content
        Assert.Contains("partial class Person", text);
        Assert.Contains("override string ToString()", text);
        Assert.Contains("Name = {Name}", text);
        Assert.Contains("Age = {Age}", text);
    }

    [Fact]
    public void ReportsError_WhenClassNotPartial() {
        var source = """
            using MyGenerators;

            namespace TestApp;

            [AutoToString]
            public class NotPartial {
                public string Name { get; set; } = "";
            }
            """;

        var result = RunGenerator<AutoToStringGenerator>(source);

        var diagnostic = Assert.Single(
            result.Diagnostics,
            d => d.Id == "ATOS001");

        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.Contains("NotPartial", diagnostic.GetMessage());
        Assert.Contains("partial", diagnostic.GetMessage());
    }

    [Fact]
    public void HandlesClassWithNoProperties() {
        var source = """
            using MyGenerators;

            namespace TestApp;

            [AutoToString]
            public partial class Empty { }
            """;

        var result = RunGenerator<AutoToStringGenerator>(source);

        Assert.Empty(result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

        var generated = Assert.Single(
            result.Results[0].GeneratedSources,
            s => s.HintName == "Empty.AutoToString.g.cs");

        var text = generated.SourceText.ToString();
        Assert.Contains("Empty {  }", text);
    }

    [Fact]
    public void HandlesStruct() {
        var source = """
            using MyGenerators;

            namespace TestApp;

            [AutoToString]
            public partial struct Point {
                public double X { get; set; }
                public double Y { get; set; }
            }
            """;

        var result = RunGenerator<AutoToStringGenerator>(source);

        Assert.Empty(result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

        var generated = Assert.Single(
            result.Results[0].GeneratedSources,
            s => s.HintName == "Point.AutoToString.g.cs");

        Assert.Contains("partial struct Point", generated.SourceText.ToString());
    }

    [Fact]
    public void CachingWorks_UnchangedInput() {
        var source = """
            using MyGenerators;

            namespace TestApp;

            [AutoToString]
            public partial class Cached {
                public string Value { get; set; } = "";
            }
            """;

        var compilation = CreateCompilation(source);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AutoToStringGenerator());

        // First run
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var comp1, out _);

        // Second run with same compilation (simulates no-change edit)
        driver = driver.RunGeneratorsAndUpdateCompilation(comp1, out _, out _);
        var result = driver.GetRunResult();

        // Verify caching
        var outputSteps = result.Results[0].TrackedOutputSteps
            .SelectMany(s => s.Value)
            .SelectMany(s => s.Outputs);

        Assert.All(outputSteps, output =>
            Assert.Equal(IncrementalStepRunReason.Cached, output.Reason));
    }

    // --- Helpers ---

    private static GeneratorDriverRunResult RunGenerator<TGenerator>(string source)
        where TGenerator : IIncrementalGenerator, new() {
        var compilation = CreateCompilation(source);
        var generator = new TGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out _);
        return driver.GetRunResult();
    }

    private static CSharpCompilation CreateCompilation(string source) {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .Cast<MetadataReference>()
            .ToList();

        return CSharpCompilation.Create(
            "TestAssembly",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }
}
