// <auto-generated/> - Sample code for learning purposes
// A minimal incremental source generator using C# 14 patterns, K&R style.
// Target framework: netstandard2.0 | Language: C# 14 (LangVersion=latest)

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MyGenerators;

/// <summary>
/// Generates a ToStringFast() method for classes annotated with [AutoToString].
/// Demonstrates: ForAttributeWithMetadataName, PostInitializationOutput, model extraction.
/// </summary>
[Generator]
public sealed class AutoToStringGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        // Step 1: Inject the marker attribute into the compilation
        context.RegisterPostInitializationOutput(static ctx => {
            ctx.AddSource("AutoToStringAttribute.g.cs", """
                // <auto-generated/>
                namespace MyGenerators;

                /// <summary>
                /// Marks a class for compile-time ToString() generation.
                /// The class must be declared as partial.
                /// </summary>
                [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
                internal sealed class AutoToStringAttribute : System.Attribute { }
                """);
        });

        // Step 2: Find all types annotated with [AutoToString]
        var typeModels = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "MyGenerators.AutoToStringAttribute",
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (ctx, ct) => {
                ct.ThrowIfCancellationRequested();

                var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                var isPartial = ctx.TargetNode is TypeDeclarationSyntax decl
                    && decl.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword);

                var properties = typeSymbol.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(p => p.DeclaredAccessibility == Accessibility.Public
                        && !p.IsStatic
                        && p.GetMethod is not null)
                    .Select(p => new PropertyModel(p.Name, p.Type.ToDisplayString()))
                    .ToImmutableArray();

                return new TypeModel(
                    Name: typeSymbol.Name,
                    Namespace: typeSymbol.ContainingNamespace.IsGlobalNamespace
                        ? null
                        : typeSymbol.ContainingNamespace.ToDisplayString(),
                    IsPartial: isPartial,
                    IsValueType: typeSymbol.IsValueType,
                    Properties: properties,
                    Location: typeSymbol.Locations.FirstOrDefault()
                );
            }
        );

        // Step 3: Generate source for each type
        context.RegisterSourceOutput(typeModels, static (spc, model) => {
            // Report diagnostic if not partial
            if (!model.IsPartial) {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "ATOS001",
                        "Type must be partial",
                        "Type '{0}' must be declared as partial to use [AutoToString]",
                        "AutoToString",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    model.Location,
                    model.Name));
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");

            if (model.Namespace is not null) {
                sb.AppendLine($"namespace {model.Namespace};");
                sb.AppendLine();
            }

            var typeKeyword = model.IsValueType ? "struct" : "class";
            sb.AppendLine($"partial {typeKeyword} {model.Name} {{");
            sb.AppendLine("    public override string ToString() {");
            sb.Append($"        return $\"{model.Name} {{ ");

            for (var i = 0; i < model.Properties.Length; i++) {
                var prop = model.Properties[i];
                if (i > 0) sb.Append(", ");
                sb.Append($"{prop.Name} = {{{prop.Name}}}");
            }

            sb.AppendLine(" }\";");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{model.Name}.AutoToString.g.cs", sb.ToString());
        });
    }
}

// --- Model Types (equatable for caching) ---

public readonly record struct TypeModel(
    string Name,
    string? Namespace,
    bool IsPartial,
    bool IsValueType,
    ImmutableArray<PropertyModel> Properties,
    Location? Location
);

public readonly record struct PropertyModel(
    string Name,
    string TypeName
);
